Server:
  RunMode: debug
  HttpPort: 8000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  ContextTimeout: 0
  ContextTimeoutType: ms
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8000/static
  UploadImageMaxSize: 5 # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
DataBase:
  DBType: mysql
  Username: user
  Password: 1q2w3e4R!
  Host: mysql:3306
  DBName: blog_service
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: eddycjy
  Issuer: blog-service
  Expire: 7200
Email:
  Host: smtp.126.com
  Prot: 445
  UserName: feichefly@126.com
  Passeord: VXMCARTWSOXKACCX
  From: feichefly@126.com
  IsSSL: true
  To:
    - 414527086@qq.com